### ISSUE TITLE
パッケージングの問題

### ISSUE THREAD

**Issue by syohex** [muddydixon/Data-ObjectGenerator#1]
CPANにアップしているものに問題がいくつか見れました。
- 依存モジュール(String::Random, Config::JSON)の記述漏れ
- ObjectGenerator.pmのバグ発見時の連絡先が他のモジュールになっている
- VERSIONが CPANにアップされているものとずれている

他には
- bin以下のファイルをインストールするのであれば EXE_FILESを指定する必要がある
- EXE_FILESで指定するファイルは '#!/usr/bin/env perl'ではなく '#!perl' or "#!/usr/bin/perl"等にする
- .git/が含まれている

などが気になりました。

CPANにアップする前に必要となる手順については[こちら](http://blog.endeworks.jp/d-6/2008/03/perlmake.html)が参考になります。

なおアップロードする際は shipitというコマンドを使うと簡単に行えます。
VERSION変数の自動インクリメント、VCSのタグ打ちとう行なってくれますし、
アップする際不都合な点があれば指摘してくれます。shiptitについてはググれば
すぐに出てくるかと思います。

**Comment by muddydixon** [comment]
大変遅くなりましたが、ありがとうございます。
あのあといろいろ調べて、一度削除いたしました。

いろいろと反省踏まえてアップしたいと思います。
(shipitもあのあと、気づきました)
